# MapLevel
chapter: 1 # 章节
map: 1 # 地图
fleet_id: 1 # 舰队编号
fleet_ships: [] # TODO: 舰队船只，未实现
repair_mode: 0 # TODO：修理方案，未实现
selected_nodes: [] # 选择要打的节点，白名单模式，一旦到达不要的节点就SL
fight_condition: 1 # 战况选择

# NodeLevel
node_defaults:
  # 索敌阶段
  SL_when_spot_enemy_fails: False # 索敌失败时是否SL
  # 战斗选择阶段
  detour: False # 是否迂回
  SL_when_detour_fails: False # 是否迂回失败后退出
  # 阵型选择阶段
  formation: 3 # 正常情况阵型选择，1-5
  formation_when_spot_enemy_fails: [False, 3] # True启用，索敌失败时阵型选择，1-5
  # 夜战选择阶段
  night: False # 是否夜战
  # 前进选择阶段
  proceed: False # 结束后是否继续

  # 特殊情况
  supply_ship_mode: 0 # 0：无额外操作  1：有补给舰则战斗，否则撤退
